Sprint1
BenoitManhes/Lunabee_Test pull request #1
Opened 2020-08-04 11:30 UTC by BenoitManhes

- Create the Application
- Create repository to download data : Flow not used for LiveData just now
- Display Data in a RecyclerView

2020-08-05 09:01 UTC, qmetzler-luna requested changes
- Coding style is not respected

2020-08-05 09:01 UTC, qmetzler-luna commented on app/src/main/java/com/example/lunabeeusers/ui/overview/UserOverviewFragment.kt
> +        ViewModelProviders.of(this).get(UserOverviewViewModel::class.java)
Deprecated

2020-08-05 09:01 UTC, qmetzler-luna commented on app/src/main/java/com/example/lunabeeusers/ui/overview/UserListAdapter.kt
> +//                right = spaceHeight
Don't leave commented code

2020-08-05 09:01 UTC, qmetzler-luna commented on app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
First two imports are useless

2020-08-05 09:01 UTC, qmetzler-luna commented on build.gradle
> +        version_kotlin = "1.3.71"
latest version is 1.3.72

2020-08-05 09:01 UTC, qmetzler-luna commented on build.gradle
> +        version_retrofit_coroutines_adapter = "0.9.2"
The latest version is 2.9.0 + it already contains a way to use coroutines without importing another lib

2020-08-05 09:01 UTC, qmetzler-luna commented on build.gradle
> +        version_kotlin_coroutines = "1.1.0"
The latest version is 1.3.8

2020-08-05 09:01 UTC, qmetzler-luna commented on app/build.gradle
> +    implementation "com.squareup.moshi:moshi-kotlin:$version_moshi"
Useless to import moshi it's already contained in com.squareup.retrofit2:converter-moshi
You can use `MoshiConverterFactory.create()` straight in ApiService.kt and replace `@Json` by `@field:Json` in User.kt

2020-08-05 09:01 UTC, qmetzler-luna commented on app/src/main/java/com/example/lunabeeusers/data/network/ApiService.kt
> +    .addCallAdapterFactory(CoroutineCallAdapterFactory())
Should be useless

2020-08-05 09:01 UTC, qmetzler-luna commented on app/src/main/java/com/example/lunabeeusers/data/network/ApiService.kt
> +            Deferred<List<User>>
Should be something more like
```
@GET("users")
suspend fun getUsers(): List<User>
```

2020-08-05 09:01 UTC, qmetzler-luna commented on app/src/main/java/com/example/lunabeeusers/ui/overview/UserOverviewViewModel.kt
> +        var getUsersDeferred = UsersApi.retrofitService.getUsers()
Can be val

2020-08-05 09:01 UTC, qmetzler-luna commented on app/src/main/java/com/example/lunabeeusers/ui/overview/UserOverviewViewModel.kt
> +                var listResult = getUsersDeferred.await()
Can be val

2020-08-05 09:01 UTC, qmetzler-luna commented on app/src/main/java/com/example/lunabeeusers/ui/overview/UserOverviewViewModel.kt
> +    private var coroutineScope = CoroutineScope(viewModelJob + Dispatchers.Main)
You can use **viewModelScope** imported by _lifecycle-viewmodel-ktx_ to remove some boiler plate code

2020-08-05 09:01 UTC, qmetzler-luna commented on app/src/main/res/layout/user_overview_fragment.xml
> +            android:padding="6dp"
Dimens should never be hardcoded and always be taken from the dimens.xml file

2020-08-05 09:01 UTC, qmetzler-luna commented on app/src/main/java/com/example/lunabeeusers/ui/overview/UserOverviewFragment.kt
> +        binding.setLifecycleOwner(this)
```suggestion
        binding.lifecycleOwner = this
```

2020-08-05 09:01 UTC, qmetzler-luna commented on app/src/main/res/layout/item_user_list.xml
> +                app:firstname="@{user}"
Why are you not using user.firstname?

2020-08-05 09:01 UTC, qmetzler-luna commented on app/src/main/res/layout/item_user_list.xml
> +                app:lastname="@{user}"
Why are you not using user.lastname?

2020-08-05 09:01 UTC, qmetzler-luna commented on app/src/main/java/com/example/lunabeeusers/core/BindingAdapter.kt
> +import com.example.lunabeeusers.R
Unused imports

2020-08-05 09:01 UTC, qmetzler-luna commented on app/src/main/java/com/example/lunabeeusers/core/BindingAdapter.kt
> +            .into(imgView)
No need for an imgUri. imgUrl can be use directly.

2020-08-05 09:01 UTC, qmetzler-luna commented on app/src/main/java/com/example/lunabeeusers/data/network/ApiService.kt
> +private const val BASE_URL = "http://server.lunabee.studio:11111/techtest/"
Could be in UsersApi

2020-08-05 09:01 UTC, qmetzler-luna commented on app/src/main/java/com/example/lunabeeusers/data/network/ApiService.kt
> +    .build()
Could be in UsersApi

2020-08-05 09:01 UTC, qmetzler-luna commented on app/src/main/java/com/example/lunabeeusers/data/network/ApiService.kt
> +}
Try to have only one class by file

2020-08-05 09:01 UTC, qmetzler-luna commented on app/src/main/java/com/example/lunabeeusers/ui/overview/UserListAdapter.kt
> +    class DiffCallback : DiffUtil.ItemCallback<User>() {
Can be private

2020-08-05 09:01 UTC, qmetzler-luna commented on app/src/main/res/values/colors.xml
> +    <color name="white">#FFFFFF</color>
android:color/white already exists

2020-08-05 09:01 UTC, qmetzler-luna commented on app/src/main/res/values/styles.xml
> +        <item name="android:layout_height">wrap_content</item>
android:layout_width and android:layout_height shouldn't be in the style

2020-08-05 09:01 UTC, qmetzler-luna commented on app/src/main/res/values/styles.xml
> +        <item name="android:textSize">18sp</item>
should be in the dimens

2020-08-05 09:01 UTC, qmetzler-luna commented on app/src/main/res/values/styles.xml
> +    <style name="textview_user_item">
style should always inherit from a system one if possible. For example TextAppearance.AppCompat.Body1 here.
naming shoud also follow the convention. For example TextAppearance.App.Body

2020-08-05 09:01 UTC, qmetzler-luna commented on app/src/main/res/layout/item_user_list.xml
> +                style="@style/textview_user_item"
should be android:textAppearance

2020-08-05 11:37 UTC, merged

2020-08-06 07:55 UTC, qmetzler-luna commented
@BenoitManhes Tu n'as pas corrigé tous mes retours, C'est parce que tu veux le faire plus tard, parce que c'est pas clair ou un oublie?

2020-08-06 10:27 UTC, BenoitManhes commented
@qmetzler-luna C'est bon c'est corrigé. J'ai préféré corriger ton retour concernant retrofit_coroutines_adapter dans le Sprint2 après avoir changer l'architecture et ajouter l'injection